repos:
  - repo: local
    hooks:
      - id: update-pre-commit
        # Keep pre-commits up to date:
        # Will BREAK commit when versions did change, so commit has to be re-initiated.
        name: update all hooks to latest for no more breaking GitHub workflow runs
        language: system
        entry: pre-commit
        args:
          - autoupdate
        always_run: true
        pass_filenames: false
        fail_fast: true

  - repo: local
    hooks:
      - id: spellcheck
        name: Spell Check
        entry: codespell
        language: en
        types: [python, markdown]
  
      
    repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - "--line-length=100"
          # - "--check"
          # - "--diff"