name: Spell Check

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  pull_request:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  spell_check:
    runs-on: ubuntu-latest  # Adjust the operating system if necessary

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust the Python version if necessary

      - name: Install codespell
        run: |
          pip install codespell

      - name: Run spell check
        run: |
          codespell --check-filenames --quiet .
